add 8 homework
Elena-Hay/skypro_python_homeworks pull request #9
Opened 2024-08-07 19:37 UTC by Elena-Hay

2024-08-08 18:56 UTC, kristina71 requested changes

2024-08-08 18:56 UTC, kristina71 commented on lesson8/test_1.py
> +
название файла не отражает сути тестов
Давай дадим файлу тестов хорошее название

2024-08-08 18:56 UTC, kristina71 commented on lesson8/test_1.py
> +    assert len(body) == 2
это условие может не выполняться, если в базе уже что-то есть

2024-08-08 18:56 UTC, kristina71 commented on lesson8/test_1.py
> +    assert employee["isActive"] == False
не нашла тестов на удаление компаний и сотрудников
+ тесты за собой не удаляют тестовые данные

2024-08-12 14:26 UTC, Elena-Hay commented on lesson8/test_1.py
> +
Исправила

2024-08-12 14:26 UTC, Elena-Hay commented on lesson8/test_1.py
> +    assert len(body) == 2
Исправила

2024-08-12 14:29 UTC, Elena-Hay commented on lesson8/test_1.py
> +    assert employee["isActive"] == False
Удаление компании добавила. Отдельно удаление сотрудников не нашла в сваггере

2024-08-14 09:41 UTC, merged